### ISSUE TITLE
Add ability for an external party (like the eWallet) to sync with the OmiseGO Network

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/elixir-omg#1000]
The eWallet is currently able to sync with Ethereum by going through each block, parsing the transactions and extracting all transactions of interest. This allows the eWallet to listen for incoming transactions to its hot wallets and deposit wallets.

We need something similar from the OmiseGO Network. In order to sync, we need to get all the transactions since the beginning. The problem is that block numbers don't follow each other (`1000, `1001`, `2000`, etc.) so we need a way to retrieve the list of all blocks, in order to then query the transactions for each one of those blocks.

Note that we don't necessarily need the blocks, what we care about are the transactions, so we may be able to rely only on `/transaction.all` if that endpoint was updated to allow sorting via parameter.

Here are a few options we came up with that meet our needs:

1. Getting the list of blocks with some endpoint (`/block.all`), and for each block getting the transactions and parsing them (`/transaction.all` with `blk_num` as filter).
2. Using `/transaction.all` to go through all transactions since the beginning of time - would require to specify the sorting order.
3. Listening to transactions on Ethereum going to the childchain smart contract (committing new blocks), getting the block hash from it, and querying the block/transactions from the Watcher with that hash (if supported, and if the hash is the same :sweat_smile: ). 
4. Can't we just get the list of all blocks from the smart contract directly? If that's the case, we can just query that, parse it and get the transactions from the Watcher for each block. This bypasses the Watcher / Childchain for block retrieval (and doesn't require much work).

/discuss

**Comment by pdobacz** [comment]
Thank you for taking the time to write this down :pray: 

To reiterate, you want to pre-preocess the contents of the child chain (the transactions to date) to extract useful information, concerning some addresses of your choice (or other criteria, like currency).

That is, you don't want to rely on being able to call `transaction.all` at the moment you need this information. Is this correct?

Now onto the details:

> The problem is that block numbers don't follow each other (1000, 1001, 2000`, etc.) 

`1001` are deposit blocks, which kinda follow their own special rules. Also the ordering of a particular deposit isn't defined till after the ethereum events related gain finality. E.g. `1000 1001 2000` can easily become `1000 2000 2001` due to a reorg.

I think currently the Watcher doesn't treat (on the outside APIs) deposits as txs nor deposit blocks as blocks. They're just "deposits", UTXOs that appear out of thin air.

> able to rely only on /transaction.all if that endpoint was updated to allow sorting via parameter.
> ...
> 2. Using /transaction.all to go through all transactions since the beginning of time - would require to specify the sorting order.

I think `transaction.all` sorts [by `[desc: :blknum, desc: :txindex]`](https://github.com/omisego/elixir-omg/blob/master/apps/omg_watcher/lib/omg_watcher/db/transaction.ex) meaning that you should have the order. As noted above, it doesn't include the deposits, for other reasons.

Oh wait, what you're saying is that you'd like to specify the order as "ascending" is that it?

> 1. Getting the list of blocks with some endpoint (/block.all), and for each block getting the transactions and parsing them (/transaction.all with blk_num as filter).

Hm, similarly, if you treat deposits independently, then the list of all blocks (all blknums) is just 1000 through `last_validated_blknum`, increasing in 1000. The `last_validated_blknum` you can get from `status.get`

> 3. Listening to transactions on Ethereum going to the childchain smart contract (committing new blocks), getting the block hash from it,

I think this is an option. As soon as the block is successfully validated by the watcher, you should be able to get the contents. I'd then vote to do `transaction.all`+filter by block hash and leave `block.get` to allow Watcher2Watcher proxying (mimic `block.get` on the childchain). But not 100% sure if the last part makes sense

> 4. Can't we just get the list of all blocks from the smart contract directly? If that's the case, we can just query that, parse it and get the transactions from the Watcher for each block

An option as well:
 - you can get the top child blknum from the contract
 - you can iterate from 1000 to that by 1000 to get all the blknums

It is an alternative of (1/) where you would use `status.get`, the difference being, you might run into a not-yet-validated blknum, so I think (1/) is better

---

I think the choice here boils down to keeping the proper separation of concerns and the question how you want to handle deposits (or - do you necessarily need to handle them as blocks and transactions).

Another question from me is how would you like to discover that a new block has been validated and there's more txs to look at - push event from the Watcher? poll?

Also let me tag @Pongch for some wider product perspective here.

**Comment by InoMurko** [comment]
I think this is tackled by many sub-issues already. Closing this in favor of those. Re-open if you think I've missed the point! Ktnx <3
