### ISSUE TITLE
OMG.ChildChain.SyncSupervisor can die quietly

### ISSUE THREAD

**Issue by pdobacz** [omisego/elixir-omg#1141]
If `OMG.ChildChain.SyncSupervisor` dies (e.g. when a child process failed to restart after crashing), it dies silently, leaving `omg_child_chain` app damaged. There's no log entry, and no alarms:

```
iex(4)> OMG.ChildChain.get_alarms()
{:ok, [{{:disk_almost_full, '/snap/core/7396'}, []}]}
```
(disregard the `disk_almost_full` it's noise, there's no alarms)

### Steps to reproduce

Run a child chain instance, do `:observer.start()`, go to "Applications", select 
 `OMG.ChildChain.SyncSupervisor` and kill.

### Notes

 - `OMG.Watcher.SyncSupervisor` is a similar, except it does produce a related (but not explicit enough) log message about `BlockGetter` going down. I think same fix should apply there

**Comment by InoMurko** [comment]
hey @pdobacz have you had another thought about this?
I would simply do what we've done for ethereum client monitoring.
If `OMG.ChildChain.Monitor` or `OMG.Watcher.Monitor` receive an EXIT message in
```
# there's a supervisor below us that did the needed restarts for it's children
  # so we just ignore the exit from the supervisor, if the alarm clears, we restart it
  def handle_info({:EXIT, _from, _reason}, state) do
    {:noreply, state}
  end
``` 
raise an alarm, `unhealthy_node`, and `Logger.error` the exit. And add the alarm type to the `Health` plug of each RPC applications, so that we cut the wire for new requests.

Now this really is unrecoverable error, that would likely happen if `EthereumEventListeners` or any if it's dependencies had a bug. Do we agree on that?

**Comment by pdobacz** [comment]
> hey @pdobacz have you had another thought about this?

not in depth, no :(. So to regurgitate, the thing that I guess still bugs me is this:

We raise `alarm` on an unrecoverable error in code ran under the `Monitor`, while we crash the VM on a similar error in code ran outside this "protective umbrella". Where's the line drawn here?

I still have a hunch that we should fail louder, whenever broken code is executed. With an alarm, we're relying on a number of moving pieces (alarms themselves, `get_alarm` endpoint, datadog) to notify us about the condition, which might be anything, including cases when we don't want continue running at all.

**Comment by InoMurko** [comment]
First batch done here: https://github.com/omisego/elixir-omg/pull/1027
Second part comes with events going to Datadog.
