### ISSUE TITLE
Do not return 'spent' UTXO's in `account.get_utxos`

### ISSUE THREAD

**Issue by nicholasmueller** [omisego/elixir-omg#1150]
As a user building a transaction, I want to use `account.get_utxos` to get a list of valid utxos i can spend. Currently, returning 'spent' UTXO's mean the wallet has to keep track of utxos that have been used, or use `account.get_exitable_utxos` which is not recommended

- Use `transactions.all` if client like BE needs transaction history

**Comment by jrhite** [comment]
FYI, I'm updating `transactions.all` endpoint now to do a deep return, including all of the transactions UTXOs with data. Reference here if needed: https://github.com/omisego/elixir-omg/issues/954

**Comment by pdobacz** [comment]
Does "spent" here mean IFE-exited? Are the steps to reproduce the same as with https://github.com/omisego/elixir-omg/issues/1151 or have you spent with a child-chain transaction? 

If the former, we can merge this issue into #1151, I'm fairly sure the problem lies with ingestion of ethereum events, so a fix for `get_balance` will fix `get_utxos`.

If the latter, pls post steps to reproduce.

**Comment by nicholasmueller** [comment]
@pdobacz yes, just tried it out and "spent" here only means IFE-exited. A normal childchain-transaction will not keep the old utxo in `get_utxos` nor will `account.get_balance` reflect the "wrong" utxo
