### ISSUE TITLE
Add transaction count to block.all and block.get

### ISSUE THREAD

**Issue by okalouti** [omisego/elixir-omg#1231]
This is to implement block explorer design that shows the number of transactions for a block. 
We are currently doing this with a `SELECT` statement and would like to move the full functionality to corresponding API endpoints. 

See [here](https://gallery.io/projects/MCHbtQVoQ2HCZfx8djn6JiP_/files/MCEJu8Y2hyDScXV2LYjxdfr91NLrkIHlsQs) and [here](https://gallery.io/projects/MCHbtQVoQ2HCZfx8djn6JiP_/files/MCEJu8Y2hyDScf3vzax-9A3x4A7SaeBV8D0).

**Current behaviour**:

```
  {
      "blknum": 92000,
      "eth_height": 5364313,
      "hash": "0x87c39b60f49c18d5366d7c04b9de0d87d8b5a83dd2a4e03162a74e4aa449b483",
      "timestamp": 1572603821
    }
``` 

**Desired behaviour**:
```
 {
      "blknum": 92000,
      "eth_height": 5364313,
      "hash": "0x87c39b60f49c18d5366d7c04b9de0d87d8b5a83dd2a4e03162a74e4aa449b483",
      "timestamp": 1572603821, 
      "tx_count": 5
    }
```

**Comment by unnawut** [comment]
Discussed with @okalouti, to get the count either we sideload the transactions and let the API consumer self-count, or we add the count here and avoid returning the transaction content.

Adding the count directly here avoids heavier transactions listing, and perf impact should be low since the `transaction.blknum` is indexed.

**Comment by unnawut** [comment]
By the way, I like how you laid out Current vs Desired behaviour in this issue. Makes the issue very easy to skim and understand.
