### ISSUE TITLE
Default values for exit_processor_sla_margin can cause the watcher to not raise unchallenged exits

### ISSUE THREAD

**Issue by thec00n** [omisego/elixir-omg#1275]
### Description 
The current audit environment `73f526d` has become byzantine. Min exit period is set to 30 minutes and `exit_processor_sla_margin` was set to its default value. The watcher flagged invalid exits but never stopped forwarding tx to the chch even after a period of more than 24h. 

### Suggested Fix 
- There should be runtime fail safe checks that prevents running a watcher with values for `exit_processor_sla_margin` and finalization period that are not within ranges that make sense. 
- Check all other config parameters for watcher and child chain that have interdependencies and  implement  fail safe checks.

**Comment by InoMurko** [comment]
Do we have an idea of `ranges that make sense`?

**Comment by pdobacz** [comment]
I did some thinking on this. I think the proper way to fix this is separate the conflated `unchallenged_exit` from `invalidly_processed_exit` and have things called by their name. The conflating of those events is too much of a stop-gap solution to continue with.

Then things get easier - when an exit processes invalidly (which was Gerhard's case) we'll get a dedicated event `invalidly_processed_exit`.

And as a consequence, we'll have more freedom in setting `exit_processor_sla_margin`, which drives `unchallenged_exit`. This is because we'll then set it to something larger than `min_exit_period`, which matters in cases where `min_exit_period` is really small.

WDYT?

**Comment by InoMurko** [comment]
Sounds good!

**Comment by pdobacz** [comment]
If the `invalidly_processed_exit` proposition gets selected, note that #671 will benefit from this too. Those two issues must be done in coordination.

**Comment by pdobacz** [comment]
After a call with @thec00n:

 - `invalidly_processed_exit` split sounds reasonable, but not enough to close this issue from @thec00n PoV.
 - for now to close this here, let's do the fail safe checks (`sla_margin < exit_period`), that can be turned off (user "know's what he's doing")
 - `invalidly_processed_exit` split finds a new home :point_down:
