### ISSUE TITLE
Perform IFE tx bytes -> IFE ID locally

### ISSUE THREAD

**Issue by unnawut** [omisego/elixir-omg#1347]
As mentioned by @InoMurko, the ExitProcessor is doing a loop to convert IFE transaction bytes into the IFE ID.

**[`OMG.Watcher.ExitProcessor`](https://github.com/omisego/elixir-omg/blob/e127775/apps/omg_watcher/lib/omg_watcher/exit_processor.ex#L255-L262):**
```elixir
contract_ife_ids =
  Enum.map(
    events,
    fn %{call_data: %{in_flight_tx: bytes}} ->
      {:ok, contract_ife_id} = Eth.RootChain.get_in_flight_exit_id(bytes)
      contract_ife_id
    end
  )
```

And suggested by @boolafish, the contract is just doing some stateless conversion on the tx bytes:

**[`ExitId`](https://github.com/omisego/plasma-contracts/blob/a3acd36/plasma_framework/contracts/src/exits/utils/ExitId.sol#L53-L55):**
```solidity
function getInFlightExitId(bytes memory _txBytes) internal pure returns (uint160) {
    return uint160((uint256(keccak256(_txBytes)) >> 105).setBit(151));
}
```

So we could do this totally offchain.

**Comment by pdobacz** [comment]
Cool! Thank you for putting this in motion! My comments:

1. Should we apply the same mechanism to standard exits? It would be awesome.
2. This is related to the pending "big cleanup" of event data, where potentially the exit_ids could be included in the logs, for an alternative approach.
3. I think doing the calculation off-chain (that is, by a twin implementation in Elixir), a thorough conformance test would be needed to make sure both implementations are kept in sync. It should be a few lines of propcheck

**Comment by pdobacz** [comment]
ah, also just noticed this: https://github.com/omisego/plasma-contracts/issues/590, might be at least partially related

**Comment by InoMurko** [comment]
```
I think doing the calculation off-chain (that is, by a twin implementation in Elixir), a thorough conformance test would be needed to make sure both implementations are kept in sync. It should be a few lines of propcheck
```

is this really needed? if there was a mismatch it would really invalidate the chain, it only means the watcher has a bug processing exits, correct?

**Comment by unnawut** [comment]
> Should we apply the same mechanism to standard exits? It would be awesome.

I looked into this before and I couldn't find SE tx bytes -> SE ID anywhere in elixir-omg. If you could point me to where it's being done, lemme know!

**Comment by unnawut** [comment]
> 3. I think doing the calculation off-chain (that is, by a twin implementation in Elixir), a thorough conformance test would be needed to make sure both implementations are kept in sync. It should be a few lines of propcheck

I'm new to propcheck. Can you point me to some code?

**Comment by pdobacz** [comment]
@unnawut 

> I looked into this before and I couldn't find SE tx bytes -> SE ID anywhere in elixir-omg. If you could point me to where it's being done, lemme know!

hm, indeed we don't, we consume the `exit_id` which is in the event for SE case, :+1: 

> I'm new to propcheck. Can you point me to some code?

A propcheck-based example of a conformance test (for tx encoding and hashing) is https://github.com/omisego/elixir-omg/blob/master/apps/omg_conformance/test/omg_conformance/conformance/signature_property_test.exs. In short:
  - it uses a special contract to access the transaction decoding code on solidity end. This is not necessary at all in your case, since you could use the `getStandardExitId` that already exists
  - it defines some generators for payment transactions. In your case not needed, just propcheck's  `binary()` will do. But see a note on propcheck below
  - it then calls both `Elixir` and `Solidity` implementations to see if they do the same thing. In the encoding and hashing case it also goes an extra mile and verifies that distinct txs have different encodings/hashings; in your case this is probably overkill, just `elixir_result == solidity_result` comparison.

However, indeed, employing property test might sound overkill, considering there's a `keccak256` at the very beginning of the routine. So I think a smaller option to just do a `elixir_result == solidity_result` on 1 (one) exemplary `txbytes` binary would give you like ~85% of the desired coverage.

Propcheck would only put more coverage on the `keccak256` implementations conformance.

So this somewhat addresses @InoMurko 's concern - a non-propcheck conformance is an even lower-hanging fruit.

To further answer Ino's comment whether this is needed, with or without propcheck, I think yes. I think the non-conformance cases uncovered for encoding & hashing proved this and the effort is small. You've got your back covered in case the implementations drift and also "bug in the Watcher" in this case is technically a security issue (e.g. not able to challenge), which will be hard to find (`status 0x0` transaction failures).

**Comment by unnawut** [comment]
Okayy. So what's remaining is "`elixir_result == solidity_result` comparison".

I have a unit-ish test at https://github.com/omisego/ex_plasma/pull/41/files#diff-cd1de5d8b57e32a0529bc21db58b8357 but those values were ran-copied-pasted manually. I definitely like to test against an actual EVM.

Last question on this is, I think it makes sense to do this `elixir_result == solidity_result` in `ex_plasma` where the elixir implementation is. Sounds good? Or do we need it in `elixir-omg/omg_conformance` too?

**Comment by InoMurko** [comment]
afaik the plan was to move all the existing `elixir-omg/omg_conformance` tests into ex_plasma. I don't see a reason why you would need them in elixir-omg.
