### ISSUE TITLE
Arbitrary Data Transaction Field

### ISSUE THREAD

**Issue by kasima** [omisego/elixir-omg#192]
The eWallet team and @kfichter would like to have a metadata field as part of the transaction format. This would be an arbitrary byte field. It opens up multiple use cases:

- allows multiple eWallets to coordinate by internal wallet ids
- can run game actions on-chain (e.g. recording chess moves)
- storing immutable data alongside a transaction

The field does not have to be very wide. Please discuss concerns here and come to a decision.

@T-Dnzt @robinclart @whoisjeremylam @kevsul @paulperegud @pdobacz

**Comment by kfichter** [comment]
My feeling is that this gets us closer to needing a bitcoin-like fee model where users can pay to include more transaction data. There should definitely be a fee for using the field to disincentize wasting space (even if it's fixed size).

**Comment by whoisjeremylam** [comment]
For context, here is the equivalent in Bitcoin https://en.bitcoin.it/wiki/OP_RETURN. The size for OP_RETURN was 40 bytes and was increased to 80 bytes (http://www.talkcrypto.org/blog/2016/12/30/op_return-40-to-80-bytes/). OP_RETURN is designated as prunable because nodes can choose to delete or not store this data.

Use of the data field is very useful for co-coordinating payments. The data field could contain a correlation_id that relates to instructions on where a payment should be directed.

Would the introduction of this field add any complications to checkpointing or to other designs that reduce the history? It seems that applications that require this data must keep the full transaction history.

**Comment by pdobacz** [comment]
@whoisjeremylam @T-Dnzt @kasima would a hash-worth of bytes (32) be enough for all use cases?

**Comment by kasima** [comment]
32 bytes seems like plenty of space. I'm going to move this into the Tracker board.
