### ISSUE TITLE
Path is a directory but has no mix.exs

### ISSUE THREAD

**Issue by jbunce** [omisego/elixir-omg#659]
```
childchain-0 childchain warning: path "apps/omg_child_chain" is a directory but it has no mix.exs. Mix won't consider this directory as part of your umbrella application. Please add a "mix.exs" or set the ":apps" key in your umbrella configuration with all relevant apps names as atoms
```

**Comment by InoMurko** [comment]
Could you please provide the environment you encountered this and what did you do/context?

**Comment by pdobacz** [comment]
> Could you please provide the environment you encountered this and what did you do/context?

I second this question. If this appears when running `v0.1`, it seems that the directory structure is tainted with `master` directories and `mix` is complaining. The tainting possibly caused by some `git` operations preceding the `mix run`? This would be strange however, I regularly bounce between `v0.1` and `master` and I'm getting various weirdness, but never this specific warning.

What path is the source code exactly taking, starting from `git clone` or equiv?

**Comment by InoMurko** [comment]
Please reopen if it’s still an issue.
