### ISSUE TITLE
Transaction metadata should not be _required_ to be 32 bytes in length

### ISSUE THREAD

**Issue by kevsul** [omisego/elixir-omg#688]
Currently the transaction metadata field has to be 32 bytes long.
If I add metadata that's shorter than that, it fails (with a `submit:malformed_metadata` exception).
I guess I could pad the data to the correct length, but then when I retrieve metadata from a transaction it may not be obvious how to 'unpad' it.
e.g. if the metadata I want to add is `007`, padded it's `00000000000000000000000000000007`; but 'unpadded' would be just `7`
(a bit of a contrived example, but you get the idea)

Can we make metadata be a variable length up to a maximum of 32 bytes?

**Comment by pnowosie** [comment]
One place I can see which would be tricky is EIP-712 again. Metamask currently doesn’t support variable length arrays - and that’s the reason you can see a bunch of zeros even if your tx contains no metadata. So shorter metadata still would need to be extended to 32 bytes before signing. Which is dangerous, e.g. ‚07’ and ‚007’ will be treated the same.

Probably easiest way to have it is to introduce some revertable encoding schema  on client side. Sorry 😢

**Comment by Pongch** [comment]
so you are saying that no matter what the data has to be filled to 32 bytes before it could be signed ? @pnowosie  It that case it might have to be the responsibility of the client to make sure it is padded ?

**Comment by pnowosie** [comment]
> so you are saying that no matter what the data has to be filled to 32 bytes before it could be signed ? 

Correct. This is current implementation limitation derived from MetaMask/metamask-extension#2986

Uncertainty regarding metadata use case (my opinion :trollface:). 
From our side we offer 32 bytes available, if not provided for signature 32 zero-bytes is used.
This field has the meaning only to the client, so if (s)he want less bytes then has to expand it to 32-bytes in reversible way.

**Comment by Pongch** [comment]
Started some discussion with the Integration team. Padded 32 bytes metadata will work fine for their uses 👌

**Comment by boolafish** [comment]
> One place I can see which would be tricky is EIP-712 again. Metamask currently doesn’t support variable length arrays

(Might be out of topic of this thread :P )
Just curious, this seems like we cannot have dynamic length of `inputs[]` and `outputs[]` in a tx, is it correct? I am a bit worried about this because we would like our batch settlement tx to have variable length of inputs and outputs if possible :( Curious if there is a way to get out of this?

**Comment by kevsul** [comment]
@boolafish How many inputs and outputs can a batch settlement tx have? 
Currently a tx can have up to 4 inputs and outputs. We kind of fake it being dynamic by padding the 'unused' inputs and outputs with null data (0x0000...).

Is that a possible solution for what you have in mind?

**Comment by whoisjeremylam** [comment]
I briefly discussed with @kasima and @Pongch. Let's finalise requirements first for the DEX settlements first and worry about this later. We can potentially bring back an old signing method. EIP712 signing probably isn't relevant for DEX settlements because such transactions will be automatically signed by a venue's back-office.

**Comment by boolafish** [comment]
Haha, yeah if there is no better way I am thinking about the same plan as well.
Padding 0 can still work but just not really a good option as we might pad hundreds or thousands (or more?) of inputs/outputs.

**Comment by pnowosie** [comment]
> Padding 0 can still work but just not really a good option as we might pad hundreds or thousands (or more?) of inputs/outputs.

Let me put my `3 grosze` here. Please note that current transaction already supports `n= 4` inputs / `m = 4` outputs, but 
* first it's implemented such a way that `n, m` are configurable,
* we don't require that `txbytes` (transaction sent to ch-ch are RLP encoded) contain fake, zero in/out-puts, you can have just 1 input & 0 outputs transaction (benefits operator)

Padding only happens in structural hashing algorithm because of unsupported dynamic tables in EIP-712 spec. But this is transparent to the user, and its not really padding - it just append some precomputed hashes of fake structures...

> "Premature optimization is the root of all evil"

**Comment by boolafish** [comment]
> we don't require that txbytes (transaction sent to ch-ch are RLP encoded) contain fake, zero in/out-puts, you can have just 1 input & 0 outputs transaction (benefits operator)

ah....this is what I was missing. Yeah, my main concern is to not put too many useless 0s to tx data itself.

**Comment by kevsul** [comment]
> we don't require that txbytes (transaction sent to ch-ch are RLP encoded) contain fake, zero in/out-puts, you can have just 1 input & 0 outputs transaction 

Cool, I didn't know that this had changed!

**Comment by pnowosie** [comment]
@boolafish @kevsul - I double checked RLP-encoding and what I said above is not true. Before transaction is RLP-encoded inputs / outputs are extended with empty to full 4-length arrays.
Correcting my bad here. Not sure if it makes any difference to the topic of the issue.

**Comment by kevsul** [comment]
Thanks for clarifying @pnowosie
And I think we've gone way off topic here, let's pick it up somewhere else if necessary...

**Comment by kevsul** [comment]
Closing this - 32 byte padded metadata seems to be acceptable
