### ISSUE TITLE
OMG-363 - Watcher get.block by number

### ISSUE THREAD

**Issue by achiurizo** [omisego/elixir-omg#721]
:clipboard: [PLAN-51](https://omisego.atlassian.net/browse/PLAN-51)

As a block explorer, 
I would like to receive the content of all transactions inside a child chain block based on block number,
so that I have a better way to visualize transactions based on historical data.

**Comment by pdobacz** [comment]
hm, wait, we have https://developer.omisego.co/elixir-omg/docs-ui/?url=master/informational_api_swagger.json#/Transaction/getTransactionsAll where we can filter by blknum.

 - It doesn't server all the details (we agreed at one point that for details one should rather iterate on `transaction.get(hash)`
 - it is subject to the limits (200 max I think), so it would require pagination to be fully usable I suppose
 - it doesn't mimic `block.get` from the child chain, which was the plan at some point, but I think this is not what we want here because we want to "receive the content of all transactions inside a child chain block"

So either I'm missing something or perhaps the existing endpoint will do (with the extension of pagination)

**Comment by pdobacz** [comment]
as discussed, only pagination is missing #725
