### ISSUE TITLE
Transaction & Blocks table empty in watcher DB

### ISSUE THREAD

**Issue by iGetSchwifty** [omisego/elixir-omg#781]
Start from fresh (Nothing omisego related on the cpu)

Get proper API token from infura

run 'docker-compose -f docker-compose-watcher-mac.yml up'

Notice that everything seems to start correctly. However, the transactions and Blocks Table has no data while the ethevents and utxos table has data.

Note: This was fixed by running 'docker-compose -f docker-compose-full-services-mac.yml up' in another process and then restarting the watcher.

**Comment by pdobacz** [comment]
Hello @iGetSchwifty

I'm not entirely sure what you're trying to accomplish nor where is the issue, but what you're seeing isn't necessarily suspicious. In particular:

> transactions and Blocks Table has no data while the ethevents and utxos table has data.

this could be the case when you only have deposits and exits done in the root chain contract, and no child chain transactions (or no child chain transactions _yet_ as your Watcher is still syncing).

The part:

> This was fixed by running...

could be some sort of coincidence too - at some later stage the transactions/blocks might have arrived in your watcher, as you allowed more time for it to sync.

`docker-compose-full-services-mac.yml` sets up a local instances of the child chain+watcher combo, which is presumably empty, so it would not have the effect you've mentioned.

Hope this helps.

Closing, since I can't figure out the exact issue here. Feel free to reopen and provide more details if anything unexpected happens

**Comment by iGetSchwifty** [comment]
No worries. I definitely had the original watcher syncing for sometime(couple days) so I doubt it was a case of the transactions arriving later but it could be I guess. I do have fiber internet and a relatively fast computer with M2 SSD. 

When running the full services it recreated the DB of the watcher which fixed the problem.
Thus my assumption was there was something wrong with running only the watcher docker-compose. As it didn’t quite setup everything correctly and left these tables empty of data. (Maybe my assumption was incorrect but I was assumed if everything was hooked up correctly and I had a valid API token for the 3rd party eth api I only needed to run the watcher docker compose not the actual full service) 

So it could be my assumption was wrong, or something got corrupted. As sometimes when I ran the docker-watcher compose, the program would would get an an elixir service not found error. Re running would usually fix it. 

Ultimately I am no longer plagued with this problem so I’m down to close it. Really opened as a safety measure to discuss. Ultimately if my assumption of being able to only run the watcher compose was wrong then there is no bug. However, if I should be able to run only the watcher compose and still have all of the tables be populated with watcher data then I believe there is a bug when running only the watcher compose and nothing else. 

Sorry about the confusion but just wanted to give a write up of some sort to try and clarify what I was seeing on my end.
