### ISSUE TITLE
standardize team on build environment

### ISSUE THREAD

**Issue by jrhite** [omisego/elixir-omg#980]
This issue references 2 PRs. Both are different approaches to help improve and speed up our build environment. The multi-stage Docker PR also attempts to standardize our actual development/build environment, so we're all on the same page.

Via Makefile: https://github.com/omisego/elixir-omg/pull/956
Via multi-stage Dockerfiles: https://github.com/omisego/elixir-omg/pull/979

I've seen many variations on our development environments:
- All development with Docker
- A VM running on Mac/Windows running some flavor of Linux
- A rented out VPS running some flavor of Linux
- Building and running some services on the native host while running other services in Docker

I think we should all be free to use the tools and toys we love. But I feel we need to standardize our development environments. On an individual level, some developers may be able to work faster with their own custom setup. But at the team level, we work slower. I want to get rid of the 'it works for me, but not for you` engineering smell.

**With everyone using Docker, if something is broken then we will all feel the pain and it will be fixed ASAP.** With individual setups, we may be unaware that there are existing problems.

I believe using Docker will help simplify things not only for us and our team velocity, but also for onboarding newhires, the open source community, etc...

Do we want to continue to manage several environments and ways of building things, including a mixing and matching of containers and bare bones, or do we want to stick with Docker only? 

If we do want to standardize on Docker I'm open to any feedback on my PR.

If we don't want to standardize on Docker, alternatives are fine, but as a team, it is my hope we can decide to standardize on some common development environment. 

All of this partly a matter of preference and neither approach is necessarily right or wrong, but clearly a team consensus for either approach is highly desirable.

Check out the PRs and let the code speak for itself! :smile:

If you made it this far, thank you for your reading! 🙏  Looking forward to hearing from everyone!

**Comment by sirn** [comment]
I have a counterpoint :wink: Since we’re an open source project and expect _anyone_ to run these components (as oppose to SaaS deployment where we’re in control), itmight actually be better to have people running different environments, so that we can detect errors that are not found in Docker image (e.g. incompatible library versions).

Still, I think it’s good to have Docker as a baseline. The approach we use in `ewallet` is to have a `builder` image that has all dependencies require to build the application and use it for both building prod image and dev image (which has benefit of able to persist build artifacts, reducing the time to do `mix release`). Makefile is used for building: we’re not expecting everyone to use `docker build` to build the production artifacts (due to reason above) so `make prod` is the actual endpoint where building happens. 

In ewallet we have `docker-gen.sh` which generates [`docker-compose.yml`](https://github.com/omisego/ewallet/blob/f311e1d55055379b0d71b77ba0d68ff99ce61d2d/docker-gen.sh) according to the use case, e.g. for evaluation purpose (which uses artifact from Docker Hub) or for dev (which uses builder image with volume mounts for build artifacts). Makefile+docker-gen has been working great for us across many different environments (especially me, who runs Ubuntu, FreeBSD and Mac depending on the phase of the moon).

**Comment by InoMurko** [comment]
I second @sirn because a large part of his work has been adapted into `elixir-omg` not only because it's great practice and as fast as it can be with the tools we have but also because it aligns us with ewallets deployment. Ewallet has been using the same process for the last year. So it's rather thoroughly tested. 
And to chip in on Makefiles, our Makefile (and ewallets) is tested every CircleCI run. 

_In my opinion, #979 does not add anything new that we don't already have._

The problem with standardization (in this case) is two fold: 
- you can't force anyone to use something you think it's best (you can only declare what you support, but you can only deprecate things you made yourself). So declaring we don't support barebone releases is like saying we don't support `vim`. It's there whether you like it or not. :) and people will open files with them. 
- And forcing everyone to use docker is not a great experience. OSx and Docker are not the best partners either.

With the following weeks, we will all be able to run all services barebone with rapid build process as #956 implies. Which is going to be faster then any docker build, because of `dev` settings that releases support. But it's a work in progress and I just can't do everything at once. Also, the biggest issue with compiling here was rocksdb, but with 1.3.2, rocksdb supports hooking itself to local installations, making compiling it very fast.

**Comment by jrhite** [comment]
Thank you @sirn and @InoMurko for your thoughts. I'd just like to respond to some things and then I'll step back for a while. I hope to hear back from you guys and hope others chime in as well.

@sirn 
> Since we’re an open source project and expect anyone to run these components (as oppose to SaaS deployment where we’re in control), itmight actually be better to have people running different environments, so that we can detect errors that are not found in Docker image (e.g. incompatible library versions).

Our production images are built from the Docker image. Why do we want to detect errors not found in the Docker image? If someone outside OMG found a non-docker bug would we then spend our time debugging it? If so, why?

I do agree that, anyone in the open source community are free to do whatever they please.

@InoMurko 
> it's great practice and as fast as it can be with the tools we have

No doubt we have a great team building great stuff. However, there's always room for improvement. The Docker community has something to say about our current practices. I recommend you guys read this [Docker multi-stage page](https://docs.docker.com/develop/develop-images/multistage-build/) if you haven't already. It has many great tips that will help us.

It particularly points out a specific 'Docker smell' we currently have that has snagged me many times before:
> When you run the build.sh script, it needs to build the first image, create a container from it to copy the artifact out, then build the second image. Both images take up room on your system and you still have the app artifact on your local disk as well.

Not only do the artifacts take up space (not a big deal), but if you forget to delete them they create unpredictable builds.

> In my opinion, #979 does not add anything new that we don't already have.

It specifically adds 3 things we don't have:
1. A prebuilt image with our mix dependencies also built.
2. No build artifacts on local machine.
3. Smaller release images.

Regarding your 2 bullet points about standardization, I hear you. If people want to use vim or build our stuff however they want, let them do so. I don't like it when others tell me how to do things too.

However, with Docker we provide the easy path, the path of least resistance. Docker is our gold standard. We release to production with it. Internally why do we not want our team to standardize on it?

What are the benefits of not standardizing on Docker? Or not standardizing on anything for that matter?

The benefits of standardizing are a lot! Most importantly we save a lot of time and money. Engineering is huge cost center. Every time someone needs to go to you (my hand is raised)  or anyone else with environment problems/questions, that takes away from yours and others feature development time. That is very expensive time! If we can reduce interruptions to you and others this is 👍

> Which is going to be faster then any docker build, because of dev settings that releases support

I'd like to know more about this when it is ready. I don't know how a build can be faster that a prebuilt image. The multi-stage Dockerfile proposal prebuilds our dependencies.

**Comment by sirn** [comment]
> Our production images are built from the Docker image. Why do we want to detect errors not found in the Docker image? If someone outside OMG found a non-docker bug would we then spend our time debugging it? If so, why?

Unfortunately we did not live in a perfect world where everyone have access to Docker (e.g. BSD, macOS/Windows [where Docker works by running an agent inside a VM]). I don't think it's a good idea for open source project to have a hard dependency on Docker.

It's OK to have Docker as a baseline, but I don't think it works as a community project if we were to dismiss everyone who found a bug using non-Docker setup as "nope, you're on your own." I learn this the hard way during eWallet workshop in Neutrino Tokyo where one third of the room, who were enthusiastic about trying out eWallet, were left in cold because we couldn't support their platform of choice.

> It particularly points out a specific 'Docker smell' we currently have that has snagged me many times before [..snip..] 

I don't think the note about `build.sh` is relevant to us. We're _not_ building the app as part of Docker's `RUN` (e.g. not using Docker as a data container), thus we did not have the "create a container, copy artifact" steps. Instead, it's mounting fs on top of Docker and writing directly to the filesystem, so no extra artifacts are created.

In current iteration, `deps` and `_build` are cached via external means, e.g. CircleCI cache, which allow us to build incrementally. Incremental build currently took [less than 2 minutes](https://circleci.com/gh/omisego/elixir-omg/19009) where rocksdb compilation is the main bottleneck (which could be put into builder image).

Whether incremental build is a good or bad idea is another thing to debate, though. :wink: 

> Smaller release images.

10~19 MB decrease seems to come from other factor rather than the methodology of the final build step itself. The way it works should essentially be the same, e.g. copying `.tar.gz` artifact and extract it into a bare image. I think alpine 3.8 vs 3.9 might be playing some role (packages in 3.9 repo is slightly smaller than 3.8)

**Comment by T-Dnzt** [comment]
> > Since we’re an open source project and expect anyone to run these components (as oppose to SaaS deployment where we’re in control), it might actually be better to have people running different environments, so that we can detect errors that are not found in Docker image (e.g. incompatible library versions).
> 
> Our production images are built from the Docker image. Why do we want to detect errors not found in the Docker image? If someone outside OMG found a non-docker bug would we then spend our time debugging it? If so, why?
> 

I'm gonna agree with Sirn here. This is open source, and you can't control what people will do with the project. As maintainers, it's our duty to ensure that our code can be used by anyone, on any platform. Sure, we won't be actually writing and testing the support for all of them right now, but people can submit issues and PRs when they're having trouble. 

I think it's important not to lock ourselves in a standard that everyone has to follow and reject all the other options. We can have a recommended or preferred way of running things, but it shouldn't go past that IMO. Docker can be that recommended way, but personally I won't be using it for development because it's too much of a pain most of the time (if things can be ran without it). Still great for things like testing PRs! And the work @InoMurko is doing with #956 looks pretty yummy with its hybrid approach.

For __how we do Docker__, I don't have a super strong opinion, but things have always worked pretty well for the eWallet with the work @sirn did, so I don't really see a reason to do it any differently.

**Comment by pdobacz** [comment]
> Docker can be that recommended way, but personally I won't be using it for development because it's too much of a pain most of the time (if things can be ran without it).

same here, well put. To me, being able to do daily development without docker getting in the way is a big advantage. Standarization is good, I'd very much like to avoid locking ourselves out of the possibility of developing without docker.

**Comment by achiurizo** [comment]
> I think it's important not to lock ourselves in a standard that everyone has to follow and reject all the other options. We can have a recommended or preferred way of running things, but it shouldn't go past that IMO. 

FWIW I found a lot of value building the application in Docker when I first started working with the project. It was nice having a 'clean' environment and building it consistently for me with it. This of course has changed over time as a lot of fixes have been pushed out to really hone down on building the application.

I agree this is open source and we should realize everyone has their preferred way to build it, the value docker has is still pretty great(especially since I'm not on OSX anymore) and I think @InoMurko's hybrid approach really meets it in the middle for building the application outside of it and leveraging docker to spin up the services the application relies on.

**Comment by jrhite** [comment]
Thanks all for your thoughts and opinions.

The good news here is it seems like there is overwhelming consensus on the direction we want to head! 😄

I'll close this issue and this PR shortly. I guess we can consider this WIP a RIP #979

@InoMurko I still want to poke you about something though. We can still make a combined image which includes our prebuilt dependencies. How about we give that a shot?

**Comment by InoMurko** [comment]
Can't imagine how that would work, but will review a PR if you make one! :)

**Comment by jrhite** [comment]
Scroll up! 😉  The PR is in this issue's description. #979  Specifically see the `Dockerfile.omg-dev-env` file.

We don't have to incorporate everything in the PR, but that setup was working very well for me.

**Comment by jrhite** [comment]
@InoMurko 
> That only makes sense for development

For development the idea was developers using docker would use both `Dockerfile.omg-dev-env` and `Dockerfile.omg-service-env`. That's the developer world.

But if you continue along the Dockerfiles you'll see `Dockerfile.omg-service-release`. This uses the same Dockerfile pipeline and produces release images.

The command in the PR to build a release is (put into a Makefile of shell script of course is):

```
docker build -t omg-erlang-env --target omg-erlang-env - < docker/Dockerfile.omg-erlang-env \
  && docker build -t omg-elixir-env - < docker/Dockerfile.omg-elixir-env \
  && docker build -t omg-dev-env --target omg-dev-env -f docker/Dockerfile.omg-dev-env . \
  && docker build --build-arg SERVICE=child_chain --build-arg RELEASE_VERSION=0.2.2+ --build-arg SHA=`git rev-parse --short=7 HEAD` -t omg-service-env-child_chain -f docker/Dockerfile.omg-service-env . \
  && docker build --build-arg SERVICE=watcher --build-arg RELEASE_VERSION=0.2.2+ --build-arg SHA=`git rev-parse --short=7 HEAD` -t omg-service-env-watcher -f docker/Dockerfile.omg-service-env . \
  && docker build --build-arg SERVICE=child_chain --build-arg RELEASE_VERSION=0.2.2+ --build-arg PORT=9656 --build-arg SHA=`git rev-parse --short=7 HEAD` -t omg-service-release-child_chain -f docker/Dockerfile.omg-service-release . \
  && docker build --build-arg SERVICE=watcher --build-arg RELEASE_VERSION=0.2.2+ --build-arg PORT=7434 --build-arg SHA=`git rev-parse --short=7 HEAD` -t omg-service-release-watcher -f docker/Dockerfile.omg-service-release .
```

> There's also the issue of invalidating the image if mix.lock changes.

That's correct. My intention was that we would use CircleCI or something to publish a new 'dependency' image to omisegoimages whenever a dependency changes.

**Comment by InoMurko** [comment]
If I imagine this correctly, this would make the deployment pipeline faster, because it doesn't need to build `deps`? 

So the step where we build a release is this:
```
docker-watcher-prod:
	docker run --rm -it \
		-v $(PWD):/app \
		-v $(IMAGE_BUILD_DIR)/deps:/app/deps \
		-u root \
		--entrypoint /bin/sh \
		$(IMAGE_BUILDER) \
		-c "cd /app && if [[ OSX == $(OSFLAG) ]] ; then make clean ; fi && make build-watcher-prod"
```
So instead of mounting the `local dir` -> `-v $(IMAGE_BUILD_DIR)/deps:/app/deps \` you would pull the image with `prebuilt deps` (let's say the image tag is a checksum of `mix.lock`). Have I summarized you correctly, @jrhite ?

**Comment by jrhite** [comment]
@InoMurko yes, this is correct.

**Comment by InoMurko** [comment]
Hm... They only need to be built once, since the build files are stored on your local HD. But if you think this is a pain for `devs` I'm here to give you my full support!

**Comment by jbunce** [comment]
Hey all. Late to the party here because I've been away. Let me give my two gwei.

Firstly it's great to see so many opinions on this. It means people are passionate and want to make the development process better for everyone. I like that we have a range of technical solutions being proposed here but I feel this conversation has lost sight of something important. So let's step back from implementing the tech and tooling for a moment and look at what we're trying to achieve.

We're in the business of providing open access financial services for everyone. The way that we're doing that is by providing APIs to third parties to build on. We don't expect the open source community to be contributing to the development of `elixir-omg`. And to date this year we've had two contributions from third parties. One of these contributors is now working for us. So while I appreciate the empathy for development on a range of different platforms and different users, the data isn't showing us that we need to be building tooling to support this range of environments.

Secondly, two partners are either building or hosting their own Watcher. At least initially we're not expecting people to run their own Childchain instance. So the real world usage of our services adds weight to the point that we don't need to support a range of platforms. This means we can be somewhat selfish and build the tooling we need to suit our requirements at OmiseGO.

In terms of support, nobody is own their own. We have an established channel for supporting integrators via the ODP, and we've received good feedback from partners on the speed and quality of the support given to date. 

I generally agree with @T-Dnzt's point about allowing code to be run by anyone, but we're not a standard three tier application. We run time dependent distributed systems which I think is the core of this problem. This means the infrastructure for local development is as much of a problem as the code itself.

As for how we achieve this I'm open to discussing.
